apiVersion: fabrix.io/v1alpha1
kind: FabrixSystemSecurityGroup
metadata:
  name: 7-9-8-8
  labels:
    fabrix.io/managed: true
    fabrix.io/datasource-id: a80f961d-42fa-440f-82a7-25fd390fb1ec
spec:
  displayName: 7-9-8-8
  endpointIPs:
  - 3.4.5.9/32
  origin:
    system: NSX
    originatedId: 7.9.8.8
  type: IP
